# Generated by Django 4.1.5 on 2023-04-03 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Fityfeed", "0010_auto_20200729_1800"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="phenylalinine",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5
            ),
        ),
    ]
