# Generated by Django 4.1.5 on 2023-04-24 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Fityfeed", "0011_fooditem_phenylalinine"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooditem", old_name="phenylalinine", new_name="phenylalanine",
        ),
    ]
